export const initialDoctorProfile = {
  fullName: 'Dr. Amara Okafor',
  specialty: 'Internal Medicine & Cardiology',
  medicalLicense: 'MD-882041',
  experience: '12 years',
  clinicName: 'MediVibe Specialty Clinic',
  phone: '+1 555 019 2024',
  clinicAddress: 'MediVibe Health Plaza, Suite 402',
  workingHours: '09:00 - 17:00',
  email: 'dr.amara@medivibe.health',
  avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=256',
  availabilityStatus: 'In Clinic',
};

export const initialPatients = [
  {
    id: 'p-1',
    name: 'Liam Whitfield',
    age: 54,
    gender: 'Male',
    patientCode: 'P-4821',
    condition: 'Coronary artery disease',
    status: 'Active',
    phone: '+1 555 234 5678',
    email: 'liam.w@example.com',
    bloodGroup: 'O+',
    allergies: 'Penicillin',
    lastVisit: '2024-04-14',
  },
  {
    id: 'p-2',
    name: 'Sofia Marchetti',
    age: 34,
    gender: 'Female',
    patientCode: 'P-4819',
    condition: 'Hypertension',
    status: 'Active',
    phone: '+1 555 876 5432',
    email: 'sofia.m@example.com',
    bloodGroup: 'A+',
    allergies: 'None known',
    lastVisit: '2024-04-14',
  },
  {
    id: 'p-3',
    name: 'Noah Bergström',
    age: 61,
    gender: 'Male',
    patientCode: 'P-4816',
    condition: 'Type 2 diabetes',
    status: 'Active',
    phone: '+1 555 345 6789',
    email: 'noah.b@example.com',
    bloodGroup: 'B+',
    allergies: 'Sulfa drugs',
    lastVisit: '2024-04-14',
  },
  {
    id: 'p-4',
    name: 'Priya Raman',
    age: 41,
    gender: 'Female',
    patientCode: 'P-4810',
    condition: 'Hypothyroidism',
    status: 'Discharged',
    phone: '+1 555 456 7890',
    email: 'priya.r@example.com',
    bloodGroup: 'AB+',
    allergies: 'None',
    lastVisit: '2024-04-13',
  },
  {
    id: 'p-5',
    name: 'Ethan Kowalski',
    age: 29,
    gender: 'Male',
    patientCode: 'P-4802',
    condition: 'Asthma',
    status: 'Discharged',
    phone: '+1 555 567 8901',
    email: 'ethan.k@example.com',
    bloodGroup: 'O-',
    allergies: 'Aspirin',
    lastVisit: '2024-04-12',
  },
  {
    id: 'p-6',
    name: 'Amelia Dupont',
    age: 28,
    gender: 'Female',
    patientCode: 'P-4798',
    condition: 'Migraine',
    status: 'Active',
    phone: '+1 555 678 9012',
    email: 'amelia.d@example.com',
    bloodGroup: 'A-',
    allergies: 'NSAIDs',
    lastVisit: '2024-04-11',
  },
  {
    id: 'p-7',
    name: 'Hassan Malik',
    age: 58,
    gender: 'Male',
    patientCode: 'P-4795',
    condition: 'Hyperlipidemia',
    status: 'Active',
    phone: '+1 555 789 0123',
    email: 'hassan.m@example.com',
    bloodGroup: 'B-',
    allergies: 'None',
    lastVisit: '2024-04-10',
  },
  {
    id: 'p-8',
    name: 'Grace Kimani',
    age: 36,
    gender: 'Female',
    patientCode: 'P-4790',
    condition: 'Anemia',
    status: 'Discharged',
    phone: '+1 555 890 1234',
    email: 'grace.k@example.com',
    bloodGroup: 'O+',
    allergies: 'Latex',
    lastVisit: '2024-04-09',
  },
];

export const initialAppointments = [
  {
    id: 'apt-1',
    patientId: 'p-1',
    patientName: 'Liam Whitfield',
    patientCode: 'P-4821',
    date: '2024-04-14',
    time: '09:12',
    type: 'In clinic',
    status: 'Waiting',
    reason: 'Chest pain',
  },
  {
    id: 'apt-2',
    patientId: 'p-2',
    patientName: 'Sofia Marchetti',
    patientCode: 'P-4819',
    date: '2024-04-14',
    time: '09:20',
    type: 'In clinic',
    status: 'In Progress',
    reason: 'Follow-up',
  },
  {
    id: 'apt-3',
    patientId: 'p-3',
    patientName: 'Noah Bergström',
    patientCode: 'P-4816',
    date: '2024-04-14',
    time: '09:28',
    type: 'In clinic',
    status: 'Waiting',
    reason: 'Hypertension',
  },
  {
    id: 'apt-4',
    patientId: 'p-4',
    patientName: 'Priya Raman',
    patientCode: 'P-4810',
    date: '2024-04-14',
    time: '09:05',
    type: 'Online',
    status: 'Completed',
    reason: 'Lab review',
  },
  {
    id: 'apt-5',
    patientId: 'p-5',
    patientName: 'Ethan Kowalski',
    patientCode: 'P-4802',
    date: '2024-04-14',
    time: '08:58',
    type: 'In clinic',
    status: 'Completed',
    reason: 'Consult',
  },
  {
    id: 'apt-6',
    patientId: 'p-6',
    patientName: 'Amelia Dupont',
    patientCode: 'P-4798',
    date: '2024-04-14',
    time: '11:05',
    type: 'Online',
    status: 'Upcoming',
    reason: 'Migraine flare check',
  },
  {
    id: 'apt-7',
    patientId: 'p-7',
    patientName: 'Hassan Malik',
    patientCode: 'P-4795',
    date: '2024-04-14',
    time: '11:30',
    type: 'In clinic',
    status: 'Upcoming',
    reason: 'Lipid panel assessment',
  }
];

export const initialAppointmentRequests = [
  {
    id: 'req-1',
    requestCode: 'R-101',
    patientName: 'Daniel Okafor',
    age: 47,
    type: 'In clinic',
    reason: 'ECG review after chest tightness',
    date: 'Mon 14 Apr',
    time: '10:30',
    status: 'pending',
  },
  {
    id: 'req-2',
    requestCode: 'R-102',
    patientName: 'Mei Tanaka',
    age: 29,
    type: 'Online',
    reason: 'Persistent migraine, 3 weeks',
    date: 'Mon 14 Apr',
    time: '12:00',
    status: 'pending',
  },
  {
    id: 'req-3',
    requestCode: 'R-103',
    patientName: 'Oliver Grant',
    age: 61,
    type: 'In clinic',
    reason: 'Diabetes medication review',
    date: 'Tue 15 Apr',
    time: '09:15',
    status: 'pending',
  },
  {
    id: 'req-4',
    requestCode: 'R-104',
    patientName: 'Fatima Zahra',
    age: 35,
    type: 'Online',
    reason: 'Thyroid lab results discussion',
    date: 'Tue 15 Apr',
    time: '16:00',
    status: 'pending',
  },
  {
    id: 'req-5',
    requestCode: 'R-105',
    patientName: 'Jonas Meyer',
    age: 52,
    type: 'In clinic',
    reason: 'Post-surgery follow-up',
    date: 'Wed 16 Apr',
    time: '11:45',
    status: 'pending',
  },
];

export const initialPrescriptions = [
  {
    id: 'rx-1',
    rxNumber: 'RX-2041',
    patientName: 'Sofia Marchetti',
    medicines: 'Amlodipine 5mg, Aspirin 75mg',
    date: '2024-04-14',
    status: 'Issued',
    dosage: '1-0-1',
    days: 5,
  },
  {
    id: 'rx-2',
    rxNumber: 'RX-2038',
    patientName: 'Priya Raman',
    medicines: 'Levothyroxine 50mcg',
    date: '2024-04-13',
    status: 'Dispensed',
    dosage: '1-0-0',
    days: 30,
  },
  {
    id: 'rx-3',
    rxNumber: 'RX-2035',
    patientName: 'Ethan Kowalski',
    medicines: 'Metformin 500mg',
    date: '2024-04-13',
    status: 'Dispensed',
    dosage: '0-1-1',
    days: 14,
  },
  {
    id: 'rx-4',
    rxNumber: 'RX-2030',
    patientName: 'Hassan Malik',
    medicines: 'Atorvastatin 20mg',
    date: '2024-04-12',
    status: 'Issued',
    dosage: '0-0-1',
    days: 30,
  },
];

export const initialInvoices = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-1048',
    patientName: 'Sofia Marchetti',
    date: '2024-04-14',
    consultationFee: 160.00,
    clinicalServices: 20.00,
    amount: 180.00,
    status: 'Paid',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-1047',
    patientName: 'Liam Whitfield',
    date: '2024-04-14',
    consultationFee: 200.00,
    clinicalServices: 40.00,
    amount: 240.00,
    status: 'Unpaid',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-1046',
    patientName: 'Noah Bergström',
    date: '2024-04-14',
    consultationFee: 140.00,
    clinicalServices: 20.00,
    amount: 160.00,
    status: 'Partial',
  },
  {
    id: 'inv-4',
    invoiceNumber: 'INV-1045',
    patientName: 'Priya Raman',
    date: '2024-04-13',
    consultationFee: 120.00,
    clinicalServices: 0.00,
    amount: 120.00,
    status: 'Paid',
  },
];

export const initialNotificationSettings = {
  appointmentReminders: true,
  newBookingRequests: true,
  urgentCaseAlerts: true,
  billingUpdates: false,
  emailAlerts: true,
  smsUrgentCases: true,
  desktopNotifications: false,
};
